Imported Debian patch 1.3-15

diff --git a/debian/prerm b/debian/prerm
--- a/debian/prerm
+++ b/debian/prerm
@@ -23,28 +23,25 @@ LIBRARY="/lib/snoopy.so"
 case "$1" in
     remove|upgrade|deconfigure)
         if [ -e /usr/sbin/ld.so.preload-manager ]; then
-         /usr/sbin/ld.so.preload-manager -r $LIBRARY || true
-        else
-         test -f $PRELOAD && grep $LIBRARY $PRELOAD &&
-         {
-         echo "Warning:";
-         echo "You have added $LIBRARY to your $PRELOAD file."
-         echo "Continuing with the removal of $LIBRARY without removing the"
-         echo "rerecence to $LIBRARY in $PRELOAD will render your system"
-         echo "unusable by programs that require dynamic linking."
-         echo ""
-         echo "Please continue with the removal after $PRELOAD"
-         echo "has been modified accordingly."
-         echo ""
-         echo "Press enter to continue."
-         read
-         }
+            /usr/sbin/ld.so.preload-manager -r $LIBRARY || true
+        elif [ -f $PRELOAD ] && grep $LIBRARY $PRELOAD; then
+            echo >&2 "Warning:";
+            echo >&2 "You have added $LIBRARY to your $PRELOAD file."
+            echo >&2 "Continuing with the removal of $LIBRARY without removing the"
+            echo >&2 "rerecence to $LIBRARY in $PRELOAD will render your system"
+            echo >&2 "unusable by programs that require dynamic linking."
+            echo >&2 ""
+            echo >&2 "Please continue with the removal after $PRELOAD"
+            echo >&2 "has been modified accordingly."
+            echo >&2 ""
+            echo >&2 "Terminating with error."
+            exit 1
         fi
         ;;
     failed-upgrade)
         ;;
     *)
-        echo "prerm called with unknown argument \$1'" >&2
+        echo >&2 "prerm called with unknown argument $1"
         exit 1
     ;;
 esac
